DROP TABLE IF EXISTS trips CASCADE;

-- Create trips table
CREATE TABLE trips (
  id SERIAL PRIMARY KEY NOT NULL,
  rider_id INTEGER REFERENCES riders(id) ON DELETE CASCADE,
  route_id INTEGER REFERENCES routes(id) ON DELETE CASCADE,
  departure TIMESTAMP NOT NULL,
  arrival TIMESTAMP NOT NULL,
  trip_type_id INTEGER REFERENCES types(id) ON DELETE CASCADE,
  price INTEGER NOT NULL,
  available_seats INTEGER NOT NULL
);